### ISSUE TITLE
Failed setup report on new Photon

### ISSUE THREAD

**Issue by towynlin** [spark/spark-setup-android#4]
From a tech support ticket. User eventually was able to setup using serial on his computer.

Samsung Galaxy S5 running Lollipop

1. Click ready on "Time to set up your Photon!"
2. Select photon in "Choose your Photon"
3. "Connecting to Photon" pops up. 15-20 seconds later it goes away.
4. Try again to select photon in "Choose your Photon"
5. "Connecting to Photon" pops up for 2 seconds-ish and goes away.
6. "Error. Please try running setup again after resetting your Photon and putting it back in blinking blue listen mode if needed."
7. Press OK
8. Back to "Time to set up your Photon!" screen.
9. Repeat steps 1-8
10. App crashes ("Unfortunately, Particle has stopped.")

**Comment by chobberoni** [comment]
I've seen this same issue in some of my tickets.

**Comment by TheSauceMan** [comment]
Hi, I reported this bug.  Is there a way for me to provide additional information so we can get some traction on this?

**Comment by chobberoni** [comment]
@TheSauceMan feel free to add additional information here in the comments of this PR.

**Comment by TheSauceMan** [comment]
@chobberoni sure.  I guess my question isn't where do I put the additional information, it is where do I get the information from?

**Comment by jensck** [comment]
@TheSauceMan here are a few other things which would help:
1. are you being offered a "report" button to report this bug when the app crashes?  If so, hitting that report button helps us a ton.
2. esp if you dont' get that button in item 1, if you could capture device logs leading up to and at the crash, that would help
3. your Wi-Fi AP name, the security type you're using (WPA, WPA2, etc), and if the SSID is hidden

**Comment by TheSauceMan** [comment]
Wow, sorry, I missed this.
I think I did get the report option once.
What's the best way to capture the device logs?
You want the brand of AP?  Or you want my SSID?  there's nothing special about my SSID.  It's not hidden, and uses WPA2.  Mind you, I can set the photons up manually.

**Comment by jensck** [comment]
There's an updated version of the app on the Play store.  Can you give that a spin and see if you can still reproduce this?

Thanks!

**Comment by TheSauceMan** [comment]
Hi @jensck ,

So I tried it and I have bad news and good news.  The bad news is the behavior didn't really change except that repeated attempts don't result in a crash.  It still tells me the list of Photons in blue flashing mode and when I pick one it just sits there forever.

The good news, however, is that I have a work-around, thanks to another app that I saw that tried to register a small wifi peripheral like that.  Basically the workaround is to go to Android Settings -> Wifi -> Disable "Smart network switch".  Then I was able to configure my Photon and re-enable "Smart network switch" when I was done.  The other app I used even did me the favor of automatically opening up the Wifi Settings page to turn it on and off so it was very user friendly.

Maybe you can try to understand why that android feature is interfering with the setup process and think of a work-around?

Sauce

**Comment by jensck** [comment]
Thanks for the update, that's all very helpful info!  I just discovered a potentially related issue, so hopefully we'll have a proper solution before long.

As for "Smart network switch", that's not a standard feature that I'm aware of.  Is this a Samsung device by any chance?

**Comment by TheSauceMan** [comment]
It is indeed a Samsung Galaxy S5.
I suspected it may be a Samsung customization and was impressed that the other app had dealt with it so cleanly. Still can't help but wonder if there is a way to avoid toggling the feature, which would make it better still. 
Sauce

**Comment by jensck** [comment]
Yeah, I'd _really_ like to avoid making the user do it.  Asking users of the Particle app to go to their Wi-Fi settings (even if we can provide a shortcut) would already be lame and tedious, but it'd be an absolute last resort for apps using the SDK that are targeted at the masses.

I'm crossing my fingers that the related network changes I'm working on will solve this, too, since they may stem from the same core problem.  When I have the fix put together, would you be interested in beta testing it?

**Comment by TheSauceMan** [comment]
Sure thing, if you need a hand, I can help you test.
I'll be out of town next week but may be able to slip a Photon in my suitcase. 
Sauce

**Comment by jensck** [comment]
@TheSauceMan the latest Play store release should fix this issue.  Can you confirm?

**Comment by bleathem** [comment]
I have installed the latest play store release (installed today), and my particle app still crashes unless I have the "smart network switch" option disabled.

**Comment by jensck** [comment]
@bleathem what are your device model number and Android OS version?

Also, is smart network switch enabled by default, or did you turn it on manually?

**Comment by jensck** [comment]
There's been a fix/workaround for this for a while.  Closing.
